/****************************************************************************
 * Copyright (c) 2014 - 2017 Qualcomm Technologies International, Ltd.
****************************************************************************/
/* phony_preserved_subsystems.h autogenerated by makeinclude.pl */

#ifndef PHONY_PRESERVED_SUBSYSTEMS_H
#define PHONY_PRESERVED_SUBSYSTEMS_H

#include "panic/panic_preserved.h"
#include "fault/fault_preserved.h"

#define PRESERVED_DATA_LIST(m) \
    PANIC_PRESERVED_DATA(m) \
    FAULT_PRESERVED_DATA(m)

#endif
