LIB=libhfp.a

HDRS=hfp.h hfp_enum.h

#DEFS+= -DDEBUG_PRINT_ENABLED
DEFS += -DHFP_DEBUG_LIB


OBJS=init.o \
	hfp_rfc.o \
    hfp_sdp.o \
    profile_handler.o


DOCS = hfp.html

GIFS = hfp.png


include ../Makefile.inc
