/* Copyright (c) 2016 Qualcomm Technologies International, Ltd. */
/*    */
/**
 * \file
 * Implementations of non-autogenerated streams-related trap calls
 */

#include "trap_api/trap_api_private.h"
#include <sink.h>

#if TRAPSET_CSB

Source StreamCsbSource(const bdaddr * remote_addr, uint16 lt_addr)
{
    IPC_STREAM_CSB_SOURCE ipc_send_prim;
    IPC_SOURCE_RSP ipc_recv_prim;

    BD_ADDR_T bd_addr;
    bd_addr.uap = remote_addr->uap;
    bd_addr.lap = remote_addr->lap;
    bd_addr.nap = remote_addr->nap;
    
    ipc_send_prim.remote_addr = &bd_addr;
    ipc_send_prim.lt_addr = lt_addr;
    ipc_send(IPC_SIGNAL_ID_STREAM_CSB_SOURCE, &ipc_send_prim, sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_STREAM_CSB_SOURCE_RSP, &ipc_recv_prim);
    return SOURCE_FROM_ID(ipc_recv_prim.ret);
}

bool CsbReceiverSetAfhMap(const bdaddr * remote_addr, uint16 lt_addr, AfhMap * afh_map, uint32 afh_instant)
{
    IPC_CSB_RECEIVER_SET_AFH_MAP ipc_send_prim;
    IPC_BOOL_RSP ipc_recv_prim;
    BD_ADDR_T bd_addr;

    bd_addr.uap = remote_addr->uap;
    bd_addr.lap = remote_addr->lap;
    bd_addr.nap = remote_addr->nap;

    ipc_send_prim.remote_addr = &bd_addr;
    ipc_send_prim.lt_addr = lt_addr;
    ipc_send_prim.afh_map = afh_map;
    ipc_send_prim.afh_instant = afh_instant;
    ipc_send(IPC_SIGNAL_ID_CSB_RECEIVER_SET_AFH_MAP, &ipc_send_prim, sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_CSB_RECEIVER_SET_AFH_MAP_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

#endif /* TRAPSET_CSB */

