/* Copyright (c) 2018 Qualcomm Technologies International, Ltd. */
/*    */
/**
 * \file
 * Implementations of non-autogenerated file-related trap calls
 */

#include "trap_api/trap_api_private.h"

#if TRAPSET_FILE

bool FileUnmap(const void *addr)
{
    /* On implementations where the filesystem is always accessible in the
       memory map the FileUnmap() trap can be implemented as a 'nop', detecting
       an invalid address would decrease performance in the common (successful)
       case. */
    UNUSED(addr);
    return TRUE;
}

#endif /* TRAPSET_FILE */
