/* Copyright (c) 2016 Qualcomm Technologies International, Ltd. */
/*    */
/**
 * \file
 * Implementations of non-autogenerated uart-related trap calls
 */

#include "trap_api/trap_api_private.h"

#if TRAPSET_UART

Sink StreamUartSink(void )
{
    IPC_STREAM_UART_SINK ipc_send_prim;
    IPC_SINK_RSP ipc_recv_prim;
    /*lint -e(603) allow uninitialised*/
    ipc_send(IPC_SIGNAL_ID_STREAM_UART_SINK, &ipc_send_prim,
                                                    sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_STREAM_UART_SINK_RSP, &ipc_recv_prim);
    return SINK_FROM_ID(ipc_recv_prim.ret);
}

#endif /* TRAPSET_UART */

