/* Copyright (c) 2017 Qualcomm Technologies International, Ltd. */
/*    */
/**
 * \file
 * Implementations of non-autogenerated sd-mmc-related trap calls
 */

#include "trap_api/trap_api_private.h"
#include <sdmmc.h>

#if TRAPSET_SD_MMC

bool SdMmcSlotInit(bool init)
{
    IPC_SD_MMC_SLOT_INIT ipc_send_prim;
    IPC_BOOL_RSP ipc_recv_prim;
    ipc_send_prim.init = init;
    ipc_send(IPC_SIGNAL_ID_SD_MMC_SLOT_INIT_REQ, &ipc_send_prim,
             sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_SD_MMC_SLOT_INIT_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

bool SdMmcReadData(uint8 slot, uint8* buff,
                   uint32 start_block, uint32 blocks_count)
{
    IPC_SD_MMC_READ_DATA ipc_send_prim;
    IPC_BOOL_RSP ipc_recv_prim;
    ipc_send_prim.slot = slot;
    ipc_send_prim.buff = buff;
    ipc_send_prim.start_block = start_block;
    ipc_send_prim.blocks_count = blocks_count;
    ipc_send(IPC_SIGNAL_ID_SD_MMC_READ_DATA_REQ, &ipc_send_prim,
             sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_SD_MMC_READ_DATA_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

#endif /* TRAPSET_SD_MMC */

