/**************************************************************************/
/* Copyright (c) 2019 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           7992

#define PATCH_ENTRY_CREATE_MUTE_OP               0x04003b61 /* $_create_mute_op */
#define PATCH_ENTRY_CBOPS_MUTE_ENABLE            0x04003b9b /* $_cbops_mute_enable */
#define PATCH_ENTRY_CBOPS_MUTE_RESET             0x04003ba1 /* $_cbops_mute_reset */
#define PATCH_ENTRY_TTP_UPDATE_TTP_FROM_SOURCE_TIME 0x04003bbd /* $_ttp_update_ttp_from_source_time */
#define PATCH_ENTRY_GET_BT_ADDRESS               0x04003e4d /* $_get_bt_address */
#define PATCH_ENTRY_SET_LIC_DEBUG                0x04003f6d /* $_set_lic_debug */
#define PATCH_ENTRY_AUDIO_PIOS_SET_DIRECTION     0x04004bad /* $_audio_pios_set_direction */
#define PATCH_ENTRY_AUDIO_PIOS_SET_OUTPUTS       0x04004c3b /* $_audio_pios_set_outputs */
#define PATCH_ENTRY_AUDIO_PIOS_GET_INPUTS        0x04004c77 /* $_audio_pios_get_inputs */
#define PATCH_ENTRY_AUDIO_THREAD_RPC_CALL        0x04005049 /* $_audio_thread_rpc_call */
#define PATCH_ENTRY_AUDIO_THREAD_RPC_IS_ACTIVE   0x04005113 /* $_audio_thread_rpc_is_active */
#define PATCH_ENTRY_AUDIO_THREAD_GET_RPC_ACTIVE  0x0400512d /* $_audio_thread_get_rpc_active */
#define PATCH_ENTRY_AUDIO_THREAD_OFFLOAD_IS_ACTIVE 0x04005141 /* $_audio_thread_offload_is_active */
#define PATCH_ENTRY_AUDIO_THREAD_OFFLOAD_IS_ENABLED 0x0400515d /* $_audio_thread_offload_is_enabled */
#define PATCH_ENTRY_AUDIO_THREAD_COPY_FFT_TWIDDLE 0x040050ab /* $_audio_thread_copy_fft_twiddle */
#define PATCH_ENTRY_AUDIO_THREAD_SET_UP_APTX     0x040050e7 /* $_audio_thread_set_up_aptx_offload */

#endif /* SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H */
