/*****************************************************************************
Copyright (c) 2018 Qualcomm Technologies International, Ltd.
*********************************************************************************/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: accessories.proto */

#ifndef PROTOBUF_C_accessories_2eproto__INCLUDED
#define PROTOBUF_C_accessories_2eproto__INCLUDED

#include <protobuf.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "common.pb-c.h"
#include "system.pb-c.h"
#include "transport.pb-c.h"
#include "speech.pb-c.h"
#include "calling.pb-c.h"
#include "central.pb-c.h"
#include "device.pb-c.h"
#include "media.pb-c.h"
#include "state.pb-c.h"

typedef struct _Response Response;
typedef struct _ControlEnvelope ControlEnvelope;


/* --- enums --- */

typedef enum _Command {
  COMMAND__NONE = 0,
  COMMAND__RESET_CONNECTION = 51,
  COMMAND__SYNCHRONIZE_SETTINGS = 50,
  COMMAND__KEEP_ALIVE = 55,
  COMMAND__REMOVE_DEVICE = 56,
  COMMAND__UPGRADE_TRANSPORT = 30,
  COMMAND__SWITCH_TRANSPORT = 31,
  COMMAND__START_SPEECH = 11,
  COMMAND__PROVIDE_SPEECH = 10,
  COMMAND__STOP_SPEECH = 12,
  COMMAND__ENDPOINT_SPEECH = 13,
  COMMAND__NOTIFY_SPEECH_STATE = 14,
  COMMAND__FORWARD_AT_COMMAND = 40,
  COMMAND__INCOMING_CALL = 41,
  COMMAND__GET_CENTRAL_INFORMATION = 103,
  COMMAND__GET_DEVICE_INFORMATION = 20,
  COMMAND__GET_DEVICE_CONFIGURATION = 21,
  COMMAND__OVERRIDE_ASSISTANT = 22,
  COMMAND__START_SETUP = 23,
  COMMAND__COMPLETE_SETUP = 24,
  COMMAND__NOTIFY_DEVICE_CONFIGURATION = 25,
  COMMAND__UPDATE_DEVICE_INFORMATION = 26,
  COMMAND__NOTIFY_DEVICE_INFORMATION = 27,
  COMMAND__ISSUE_MEDIA_CONTROL = 60,
  COMMAND__GET_STATE = 100,
  COMMAND__SET_STATE = 101,
  COMMAND__SYNCHRONIZE_STATE = 102
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMAND)
} Command;

/* --- messages --- */

typedef enum {
  RESPONSE__PAYLOAD__NOT_SET = 0,
  RESPONSE__PAYLOAD_CONNECTION_DETAILS = 8,
  RESPONSE__PAYLOAD_DIALOG = 14,
  RESPONSE__PAYLOAD_SPEECH_PROVIDER = 15,
  RESPONSE__PAYLOAD_CENTRAL_INFORMATION = 13,
  RESPONSE__PAYLOAD_DEVICE_INFORMATION = 3,
  RESPONSE__PAYLOAD_DEVICE_CONFIGURATION = 10,
  RESPONSE__PAYLOAD_STATE = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RESPONSE__PAYLOAD)
} Response__PayloadCase;

struct  _Response
{
  ProtobufCMessage base;
  ErrorCode error_code;
  Response__PayloadCase payload_case;
  union {
    ConnectionDetails *connection_details;
    Dialog *dialog;
    SpeechProvider *speech_provider;
    CentralInformation *central_information;
    DeviceInformation *device_information;
    DeviceConfiguration *device_configuration;
    State *state;
  }u;
};
#define RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response__descriptor) \
    , ERROR_CODE__SUCCESS, RESPONSE__PAYLOAD__NOT_SET, {0} }


typedef enum {
  CONTROL_ENVELOPE__PAYLOAD__NOT_SET = 0,
  CONTROL_ENVELOPE__PAYLOAD_RESPONSE = 9,
  CONTROL_ENVELOPE__PAYLOAD_RESET_CONNECTION = 51,
  CONTROL_ENVELOPE__PAYLOAD_SYNCHRONIZE_SETTINGS = 50,
  CONTROL_ENVELOPE__PAYLOAD_KEEP_ALIVE = 55,
  CONTROL_ENVELOPE__PAYLOAD_REMOVE_DEVICE = 56,
  CONTROL_ENVELOPE__PAYLOAD_UPGRADE_TRANSPORT = 30,
  CONTROL_ENVELOPE__PAYLOAD_SWITCH_TRANSPORT = 31,
  CONTROL_ENVELOPE__PAYLOAD_START_SPEECH = 11,
  CONTROL_ENVELOPE__PAYLOAD_PROVIDE_SPEECH = 10,
  CONTROL_ENVELOPE__PAYLOAD_STOP_SPEECH = 12,
  CONTROL_ENVELOPE__PAYLOAD_ENDPOINT_SPEECH = 13,
  CONTROL_ENVELOPE__PAYLOAD_NOTIFY_SPEECH_STATE = 14,
  CONTROL_ENVELOPE__PAYLOAD_FORWARD_AT_COMMAND = 40,
  CONTROL_ENVELOPE__PAYLOAD_INCOMING_CALL = 41,
  CONTROL_ENVELOPE__PAYLOAD_GET_CENTRAL_INFORMATION = 103,
  CONTROL_ENVELOPE__PAYLOAD_GET_DEVICE_INFORMATION = 20,
  CONTROL_ENVELOPE__PAYLOAD_GET_DEVICE_CONFIGURATION = 21,
  CONTROL_ENVELOPE__PAYLOAD_OVERRIDE_ASSISTANT = 22,
  CONTROL_ENVELOPE__PAYLOAD_START_SETUP = 23,
  CONTROL_ENVELOPE__PAYLOAD_COMPLETE_SETUP = 24,
  CONTROL_ENVELOPE__PAYLOAD_NOTIFY_DEVICE_CONFIGURATION = 25,
  CONTROL_ENVELOPE__PAYLOAD_UPDATE_DEVICE_INFORMATION = 26,
  CONTROL_ENVELOPE__PAYLOAD_NOTIFY_DEVICE_INFORMATION = 27,
  CONTROL_ENVELOPE__PAYLOAD_ISSUE_MEDIA_CONTROL = 60,
  CONTROL_ENVELOPE__PAYLOAD_GET_STATE = 100,
  CONTROL_ENVELOPE__PAYLOAD_SET_STATE = 101,
  CONTROL_ENVELOPE__PAYLOAD_SYNCHRONIZE_STATE = 102
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CONTROL_ENVELOPE__PAYLOAD)
} ControlEnvelope__PayloadCase;

struct  _ControlEnvelope
{
  ProtobufCMessage base;
  Command command;
  ControlEnvelope__PayloadCase payload_case;
  union {
    Response *response;
    ResetConnection *reset_connection;
    SynchronizeSettings *synchronize_settings;
    KeepAlive *keep_alive;
    RemoveDevice *remove_device;
    UpgradeTransport *upgrade_transport;
    SwitchTransport *switch_transport;
    StartSpeech *start_speech;
    ProvideSpeech *provide_speech;
    StopSpeech *stop_speech;
    EndpointSpeech *endpoint_speech;
    NotifySpeechState *notify_speech_state;
    ForwardATCommand *forward_at_command;
    IncomingCall *incoming_call;
    GetCentralInformation *get_central_information;
    GetDeviceInformation *get_device_information;
    GetDeviceConfiguration *get_device_configuration;
    OverrideAssistant *override_assistant;
    StartSetup *start_setup;
    CompleteSetup *complete_setup;
    NotifyDeviceConfiguration *notify_device_configuration;
    UpdateDeviceInformation *update_device_information;
    NotifyDeviceInformation *notify_device_information;
    IssueMediaControl *issue_media_control;
    GetState *get_state;
    SetState *set_state;
    SynchronizeState *synchronize_state;
  }u;
};
#define CONTROL_ENVELOPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_envelope__descriptor) \
    , COMMAND__NONE, CONTROL_ENVELOPE__PAYLOAD__NOT_SET, {0} }


/* Response methods */
void   response__init
                     (Response         *message);
size_t response__get_packed_size
                     (const Response   *message);
size_t response__pack
                     (const Response   *message,
                      uint8_t             *out);
size_t response__pack_to_buffer
                     (const Response   *message,
                      ProtobufCBuffer     *buffer);
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator);
/* ControlEnvelope methods */
void   control_envelope__init
                     (ControlEnvelope         *message);
size_t control_envelope__get_packed_size
                     (const ControlEnvelope   *message);
size_t control_envelope__pack
                     (const ControlEnvelope   *message,
                      uint8_t             *out);
size_t control_envelope__pack_to_buffer
                     (const ControlEnvelope   *message,
                      ProtobufCBuffer     *buffer);
ControlEnvelope *
       control_envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_envelope__free_unpacked
                     (ControlEnvelope *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Response_Closure)
                 (const Response *message,
                  void *closure_data);
typedef void (*ControlEnvelope_Closure)
                 (const ControlEnvelope *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    command__descriptor;
extern const ProtobufCMessageDescriptor response__descriptor;
extern const ProtobufCMessageDescriptor control_envelope__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_accessories_2eproto__INCLUDED */
