/*****************************************************************************
Copyright (c) 2018 Qualcomm Technologies International, Ltd.
*********************************************************************************/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

#ifndef PROTOBUF_C_common_2eproto__INCLUDED
#define PROTOBUF_C_common_2eproto__INCLUDED

#include <protobuf.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Transport {
  TRANSPORT__BLUETOOTH_LOW_ENERGY = 0,
  TRANSPORT__BLUETOOTH_RFCOMM = 1,
  TRANSPORT__BLUETOOTH_IAP = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TRANSPORT)
} Transport;
typedef enum _ErrorCode {
  ERROR_CODE__SUCCESS = 0,
  ERROR_CODE__UNKNOWN = 1,
  ERROR_CODE__INTERNAL = 2,
  ERROR_CODE__UNSUPPORTED = 3,
  ERROR_CODE__USER_CANCELLED = 4,
  ERROR_CODE__NOT_FOUND = 5,
  ERROR_CODE__INVALID = 6,
  ERROR_CODE__BUSY = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ERROR_CODE)
} ErrorCode;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    transport__descriptor;
extern const ProtobufCEnumDescriptor    error_code__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_common_2eproto__INCLUDED */
