/*****************************************************************************
Copyright (c) 2018 Qualcomm Technologies International, Ltd.
*********************************************************************************/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: device.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "device.pb-c.h"
void   device_battery__init
                     (DeviceBattery         *message)
{
  static const DeviceBattery init_value = DEVICE_BATTERY__INIT;
  *message = init_value;
}
size_t device_battery__get_packed_size
                     (const DeviceBattery *message)
{
  assert(message->base.descriptor == &device_battery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_battery__pack
                     (const DeviceBattery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_battery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_battery__pack_to_buffer
                     (const DeviceBattery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_battery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceBattery *
       device_battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceBattery *)
     protobuf_c_message_unpack (&device_battery__descriptor,
                                allocator, len, data);
}
void   device_battery__free_unpacked
                     (DeviceBattery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_battery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_status__init
                     (DeviceStatus         *message)
{
  static const DeviceStatus init_value = DEVICE_STATUS__INIT;
  *message = init_value;
}
size_t device_status__get_packed_size
                     (const DeviceStatus *message)
{
  assert(message->base.descriptor == &device_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_status__pack
                     (const DeviceStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_status__pack_to_buffer
                     (const DeviceStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceStatus *
       device_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceStatus *)
     protobuf_c_message_unpack (&device_status__descriptor,
                                allocator, len, data);
}
void   device_status__free_unpacked
                     (DeviceStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_information__init
                     (DeviceInformation         *message)
{
  static const DeviceInformation init_value = DEVICE_INFORMATION__INIT;
  *message = init_value;
}
size_t device_information__get_packed_size
                     (const DeviceInformation *message)
{
  assert(message->base.descriptor == &device_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_information__pack
                     (const DeviceInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_information__pack_to_buffer
                     (const DeviceInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInformation *
       device_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInformation *)
     protobuf_c_message_unpack (&device_information__descriptor,
                                allocator, len, data);
}
void   device_information__free_unpacked
                     (DeviceInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_device_information__init
                     (GetDeviceInformation         *message)
{
  static const GetDeviceInformation init_value = GET_DEVICE_INFORMATION__INIT;
  *message = init_value;
}
size_t get_device_information__get_packed_size
                     (const GetDeviceInformation *message)
{
  assert(message->base.descriptor == &get_device_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_device_information__pack
                     (const GetDeviceInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_device_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_device_information__pack_to_buffer
                     (const GetDeviceInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_device_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetDeviceInformation *
       get_device_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetDeviceInformation *)
     protobuf_c_message_unpack (&get_device_information__descriptor,
                                allocator, len, data);
}
void   get_device_information__free_unpacked
                     (GetDeviceInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_device_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_configuration__init
                     (DeviceConfiguration         *message)
{
  static const DeviceConfiguration init_value = DEVICE_CONFIGURATION__INIT;
  *message = init_value;
}
size_t device_configuration__get_packed_size
                     (const DeviceConfiguration *message)
{
  assert(message->base.descriptor == &device_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_configuration__pack
                     (const DeviceConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_configuration__pack_to_buffer
                     (const DeviceConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceConfiguration *
       device_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceConfiguration *)
     protobuf_c_message_unpack (&device_configuration__descriptor,
                                allocator, len, data);
}
void   device_configuration__free_unpacked
                     (DeviceConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_device_configuration__init
                     (GetDeviceConfiguration         *message)
{
  static const GetDeviceConfiguration init_value = GET_DEVICE_CONFIGURATION__INIT;
  *message = init_value;
}
size_t get_device_configuration__get_packed_size
                     (const GetDeviceConfiguration *message)
{
  assert(message->base.descriptor == &get_device_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_device_configuration__pack
                     (const GetDeviceConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_device_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_device_configuration__pack_to_buffer
                     (const GetDeviceConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_device_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetDeviceConfiguration *
       get_device_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetDeviceConfiguration *)
     protobuf_c_message_unpack (&get_device_configuration__descriptor,
                                allocator, len, data);
}
void   get_device_configuration__free_unpacked
                     (GetDeviceConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_device_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   override_assistant__init
                     (OverrideAssistant         *message)
{
  static const OverrideAssistant init_value = OVERRIDE_ASSISTANT__INIT;
  *message = init_value;
}
size_t override_assistant__get_packed_size
                     (const OverrideAssistant *message)
{
  assert(message->base.descriptor == &override_assistant__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t override_assistant__pack
                     (const OverrideAssistant *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &override_assistant__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t override_assistant__pack_to_buffer
                     (const OverrideAssistant *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &override_assistant__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OverrideAssistant *
       override_assistant__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OverrideAssistant *)
     protobuf_c_message_unpack (&override_assistant__descriptor,
                                allocator, len, data);
}
void   override_assistant__free_unpacked
                     (OverrideAssistant *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &override_assistant__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_setup__init
                     (StartSetup         *message)
{
  static const StartSetup init_value = START_SETUP__INIT;
  *message = init_value;
}
size_t start_setup__get_packed_size
                     (const StartSetup *message)
{
  assert(message->base.descriptor == &start_setup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_setup__pack
                     (const StartSetup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_setup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_setup__pack_to_buffer
                     (const StartSetup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_setup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartSetup *
       start_setup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartSetup *)
     protobuf_c_message_unpack (&start_setup__descriptor,
                                allocator, len, data);
}
void   start_setup__free_unpacked
                     (StartSetup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_setup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   complete_setup__init
                     (CompleteSetup         *message)
{
  static const CompleteSetup init_value = COMPLETE_SETUP__INIT;
  *message = init_value;
}
size_t complete_setup__get_packed_size
                     (const CompleteSetup *message)
{
  assert(message->base.descriptor == &complete_setup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t complete_setup__pack
                     (const CompleteSetup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &complete_setup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t complete_setup__pack_to_buffer
                     (const CompleteSetup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &complete_setup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CompleteSetup *
       complete_setup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CompleteSetup *)
     protobuf_c_message_unpack (&complete_setup__descriptor,
                                allocator, len, data);
}
void   complete_setup__free_unpacked
                     (CompleteSetup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &complete_setup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notify_device_configuration__init
                     (NotifyDeviceConfiguration         *message)
{
  static const NotifyDeviceConfiguration init_value = NOTIFY_DEVICE_CONFIGURATION__INIT;
  *message = init_value;
}
size_t notify_device_configuration__get_packed_size
                     (const NotifyDeviceConfiguration *message)
{
  assert(message->base.descriptor == &notify_device_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_device_configuration__pack
                     (const NotifyDeviceConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_device_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_device_configuration__pack_to_buffer
                     (const NotifyDeviceConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_device_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyDeviceConfiguration *
       notify_device_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyDeviceConfiguration *)
     protobuf_c_message_unpack (&notify_device_configuration__descriptor,
                                allocator, len, data);
}
void   notify_device_configuration__free_unpacked
                     (NotifyDeviceConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_device_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   update_device_information__init
                     (UpdateDeviceInformation         *message)
{
  static const UpdateDeviceInformation init_value = UPDATE_DEVICE_INFORMATION__INIT;
  *message = init_value;
}
size_t update_device_information__get_packed_size
                     (const UpdateDeviceInformation *message)
{
  assert(message->base.descriptor == &update_device_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t update_device_information__pack
                     (const UpdateDeviceInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &update_device_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t update_device_information__pack_to_buffer
                     (const UpdateDeviceInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &update_device_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpdateDeviceInformation *
       update_device_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpdateDeviceInformation *)
     protobuf_c_message_unpack (&update_device_information__descriptor,
                                allocator, len, data);
}
void   update_device_information__free_unpacked
                     (UpdateDeviceInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &update_device_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notify_device_information__init
                     (NotifyDeviceInformation         *message)
{
  static const NotifyDeviceInformation init_value = NOTIFY_DEVICE_INFORMATION__INIT;
  *message = init_value;
}
size_t notify_device_information__get_packed_size
                     (const NotifyDeviceInformation *message)
{
  assert(message->base.descriptor == &notify_device_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_device_information__pack
                     (const NotifyDeviceInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_device_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_device_information__pack_to_buffer
                     (const NotifyDeviceInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_device_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyDeviceInformation *
       notify_device_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyDeviceInformation *)
     protobuf_c_message_unpack (&notify_device_information__descriptor,
                                allocator, len, data);
}
void   notify_device_information__free_unpacked
                     (NotifyDeviceInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_device_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue device_battery__status__enum_values_by_number[4] =
{
  { "UNKNOWN", "DEVICE_BATTERY__STATUS__UNKNOWN", 0 },
  { "CHARGING", "DEVICE_BATTERY__STATUS__CHARGING", 1 },
  { "DISCHARGING", "DEVICE_BATTERY__STATUS__DISCHARGING", 2 },
  { "FULL", "DEVICE_BATTERY__STATUS__FULL", 3 },
};
static const ProtobufCIntRange device_battery__status__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex device_battery__status__enum_values_by_name[4] =
{
  { "CHARGING", 1 },
  { "DISCHARGING", 2 },
  { "FULL", 3 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor device_battery__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DeviceBattery.Status",
  "Status",
  "DeviceBattery__Status",
  "",
  4,
  device_battery__status__enum_values_by_number,
  4,
  device_battery__status__enum_values_by_name,
  1,
  device_battery__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor device_battery__field_descriptors[3] =
{
  {
    "level",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceBattery, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceBattery, scale),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceBattery, status),
    &device_battery__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_battery__field_indices_by_name[] = {
  0,   /* field[0] = level */
  1,   /* field[1] = scale */
  2,   /* field[2] = status */
};
static const ProtobufCIntRange device_battery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor device_battery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceBattery",
  "DeviceBattery",
  "DeviceBattery",
  "",
  sizeof(DeviceBattery),
  3,
  device_battery__field_descriptors,
  device_battery__field_indices_by_name,
  1,  device_battery__number_ranges,
  (ProtobufCMessageInit) device_battery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_status__field_descriptors[3] =
{
  {
    "link",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceStatus, link),
    &connection_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nfmi",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceStatus, nfmi),
    &connection_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "presence",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceStatus, presence),
    &device_presence__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_status__field_indices_by_name[] = {
  0,   /* field[0] = link */
  1,   /* field[1] = nfmi */
  2,   /* field[2] = presence */
};
static const ProtobufCIntRange device_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor device_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceStatus",
  "DeviceStatus",
  "DeviceStatus",
  "",
  sizeof(DeviceStatus),
  3,
  device_status__field_descriptors,
  device_status__field_indices_by_name,
  1,  device_status__number_ranges,
  (ProtobufCMessageInit) device_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_information__field_descriptors[8] =
{
  {
    "serial_number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, serial_number),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_transports",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DeviceInformation, n_supported_transports),
    offsetof(DeviceInformation, supported_transports),
    &transport__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, device_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, battery),
    &device_battery__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, status),
    &device_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "product_color",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceInformation, product_color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_information__field_indices_by_name[] = {
  5,   /* field[5] = battery */
  4,   /* field[4] = device_id */
  3,   /* field[3] = device_type */
  1,   /* field[1] = name */
  7,   /* field[7] = product_color */
  0,   /* field[0] = serial_number */
  6,   /* field[6] = status */
  2,   /* field[2] = supported_transports */
};
static const ProtobufCIntRange device_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor device_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInformation",
  "DeviceInformation",
  "DeviceInformation",
  "",
  sizeof(DeviceInformation),
  8,
  device_information__field_descriptors,
  device_information__field_indices_by_name,
  1,  device_information__number_ranges,
  (ProtobufCMessageInit) device_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_device_information__field_descriptors[1] =
{
  {
    "device_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetDeviceInformation, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_device_information__field_indices_by_name[] = {
  0,   /* field[0] = device_id */
};
static const ProtobufCIntRange get_device_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_device_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetDeviceInformation",
  "GetDeviceInformation",
  "GetDeviceInformation",
  "",
  sizeof(GetDeviceInformation),
  1,
  get_device_information__field_descriptors,
  get_device_information__field_indices_by_name,
  1,  get_device_information__number_ranges,
  (ProtobufCMessageInit) get_device_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_configuration__field_descriptors[2] =
{
  {
    "needs_assistant_override",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceConfiguration, needs_assistant_override),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "needs_setup",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceConfiguration, needs_setup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_configuration__field_indices_by_name[] = {
  0,   /* field[0] = needs_assistant_override */
  1,   /* field[1] = needs_setup */
};
static const ProtobufCIntRange device_configuration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor device_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceConfiguration",
  "DeviceConfiguration",
  "DeviceConfiguration",
  "",
  sizeof(DeviceConfiguration),
  2,
  device_configuration__field_descriptors,
  device_configuration__field_indices_by_name,
  1,  device_configuration__number_ranges,
  (ProtobufCMessageInit) device_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define get_device_configuration__field_descriptors NULL
#define get_device_configuration__field_indices_by_name NULL
#define get_device_configuration__number_ranges NULL
const ProtobufCMessageDescriptor get_device_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetDeviceConfiguration",
  "GetDeviceConfiguration",
  "GetDeviceConfiguration",
  "",
  sizeof(GetDeviceConfiguration),
  0,
  get_device_configuration__field_descriptors,
  get_device_configuration__field_indices_by_name,
  0,  get_device_configuration__number_ranges,
  (ProtobufCMessageInit) get_device_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor override_assistant__field_descriptors[1] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OverrideAssistant, error_code),
    &error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned override_assistant__field_indices_by_name[] = {
  0,   /* field[0] = error_code */
};
static const ProtobufCIntRange override_assistant__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor override_assistant__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OverrideAssistant",
  "OverrideAssistant",
  "OverrideAssistant",
  "",
  sizeof(OverrideAssistant),
  1,
  override_assistant__field_descriptors,
  override_assistant__field_indices_by_name,
  1,  override_assistant__number_ranges,
  (ProtobufCMessageInit) override_assistant__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define start_setup__field_descriptors NULL
#define start_setup__field_indices_by_name NULL
#define start_setup__number_ranges NULL
const ProtobufCMessageDescriptor start_setup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartSetup",
  "StartSetup",
  "StartSetup",
  "",
  sizeof(StartSetup),
  0,
  start_setup__field_descriptors,
  start_setup__field_indices_by_name,
  0,  start_setup__number_ranges,
  (ProtobufCMessageInit) start_setup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor complete_setup__field_descriptors[1] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CompleteSetup, error_code),
    &error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned complete_setup__field_indices_by_name[] = {
  0,   /* field[0] = error_code */
};
static const ProtobufCIntRange complete_setup__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor complete_setup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CompleteSetup",
  "CompleteSetup",
  "CompleteSetup",
  "",
  sizeof(CompleteSetup),
  1,
  complete_setup__field_descriptors,
  complete_setup__field_indices_by_name,
  1,  complete_setup__number_ranges,
  (ProtobufCMessageInit) complete_setup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor notify_device_configuration__field_descriptors[1] =
{
  {
    "device_configuration",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NotifyDeviceConfiguration, device_configuration),
    &device_configuration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify_device_configuration__field_indices_by_name[] = {
  0,   /* field[0] = device_configuration */
};
static const ProtobufCIntRange notify_device_configuration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor notify_device_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifyDeviceConfiguration",
  "NotifyDeviceConfiguration",
  "NotifyDeviceConfiguration",
  "",
  sizeof(NotifyDeviceConfiguration),
  1,
  notify_device_configuration__field_descriptors,
  notify_device_configuration__field_indices_by_name,
  1,  notify_device_configuration__number_ranges,
  (ProtobufCMessageInit) notify_device_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor update_device_information__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UpdateDeviceInformation, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_device_information__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange update_device_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor update_device_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpdateDeviceInformation",
  "UpdateDeviceInformation",
  "UpdateDeviceInformation",
  "",
  sizeof(UpdateDeviceInformation),
  1,
  update_device_information__field_descriptors,
  update_device_information__field_indices_by_name,
  1,  update_device_information__number_ranges,
  (ProtobufCMessageInit) update_device_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor notify_device_information__field_descriptors[1] =
{
  {
    "device_information",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NotifyDeviceInformation, device_information),
    &device_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify_device_information__field_indices_by_name[] = {
  0,   /* field[0] = device_information */
};
static const ProtobufCIntRange notify_device_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor notify_device_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifyDeviceInformation",
  "NotifyDeviceInformation",
  "NotifyDeviceInformation",
  "",
  sizeof(NotifyDeviceInformation),
  1,
  notify_device_information__field_descriptors,
  notify_device_information__field_indices_by_name,
  1,  notify_device_information__number_ranges,
  (ProtobufCMessageInit) notify_device_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue connection_status__enum_values_by_number[3] =
{
  { "CONNECTION_STATUS_UNKNOWN", "CONNECTION_STATUS__CONNECTION_STATUS_UNKNOWN", 0 },
  { "CONNECTION_STATUS_CONNECTED", "CONNECTION_STATUS__CONNECTION_STATUS_CONNECTED", 1 },
  { "CONNECTION_STATUS_DISCONNECTED", "CONNECTION_STATUS__CONNECTION_STATUS_DISCONNECTED", 2 },
};
static const ProtobufCIntRange connection_status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex connection_status__enum_values_by_name[3] =
{
  { "CONNECTION_STATUS_CONNECTED", 1 },
  { "CONNECTION_STATUS_DISCONNECTED", 2 },
  { "CONNECTION_STATUS_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor connection_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ConnectionStatus",
  "ConnectionStatus",
  "ConnectionStatus",
  "",
  3,
  connection_status__enum_values_by_number,
  3,
  connection_status__enum_values_by_name,
  1,
  connection_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue device_presence__enum_values_by_number[4] =
{
  { "DEVICE_PRESENCE_UNKNOWN", "DEVICE_PRESENCE__DEVICE_PRESENCE_UNKNOWN", 0 },
  { "DEVICE_PRESENCE_ACTIVE", "DEVICE_PRESENCE__DEVICE_PRESENCE_ACTIVE", 1 },
  { "DEVICE_PRESENCE_INACTIVE", "DEVICE_PRESENCE__DEVICE_PRESENCE_INACTIVE", 2 },
  { "DEVICE_PRESENCE_ACCESSIBLE", "DEVICE_PRESENCE__DEVICE_PRESENCE_ACCESSIBLE", 3 },
};
static const ProtobufCIntRange device_presence__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex device_presence__enum_values_by_name[4] =
{
  { "DEVICE_PRESENCE_ACCESSIBLE", 3 },
  { "DEVICE_PRESENCE_ACTIVE", 1 },
  { "DEVICE_PRESENCE_INACTIVE", 2 },
  { "DEVICE_PRESENCE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor device_presence__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DevicePresence",
  "DevicePresence",
  "DevicePresence",
  "",
  4,
  device_presence__enum_values_by_number,
  4,
  device_presence__enum_values_by_name,
  1,
  device_presence__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
