/*****************************************************************************
Copyright (c) 2018 Qualcomm Technologies International, Ltd.
*********************************************************************************/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: speech.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "speech.pb-c.h"
void   dialog__init
                     (Dialog         *message)
{
  static const Dialog init_value = DIALOG__INIT;
  *message = init_value;
}
size_t dialog__get_packed_size
                     (const Dialog *message)
{
  assert(message->base.descriptor == &dialog__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dialog__pack
                     (const Dialog *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dialog__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dialog__pack_to_buffer
                     (const Dialog *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dialog__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dialog *
       dialog__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dialog *)
     protobuf_c_message_unpack (&dialog__descriptor,
                                allocator, len, data);
}
void   dialog__free_unpacked
                     (Dialog *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dialog__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speech_settings__init
                     (SpeechSettings         *message)
{
  static const SpeechSettings init_value = SPEECH_SETTINGS__INIT;
  *message = init_value;
}
size_t speech_settings__get_packed_size
                     (const SpeechSettings *message)
{
  assert(message->base.descriptor == &speech_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech_settings__pack
                     (const SpeechSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech_settings__pack_to_buffer
                     (const SpeechSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpeechSettings *
       speech_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpeechSettings *)
     protobuf_c_message_unpack (&speech_settings__descriptor,
                                allocator, len, data);
}
void   speech_settings__free_unpacked
                     (SpeechSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speech_initiator__wake_word__init
                     (SpeechInitiator__WakeWord         *message)
{
  static const SpeechInitiator__WakeWord init_value = SPEECH_INITIATOR__WAKE_WORD__INIT;
  *message = init_value;
}
void   speech_initiator__init
                     (SpeechInitiator         *message)
{
  static const SpeechInitiator init_value = SPEECH_INITIATOR__INIT;
  *message = init_value;
}
size_t speech_initiator__get_packed_size
                     (const SpeechInitiator *message)
{
  assert(message->base.descriptor == &speech_initiator__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech_initiator__pack
                     (const SpeechInitiator *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech_initiator__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech_initiator__pack_to_buffer
                     (const SpeechInitiator *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech_initiator__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpeechInitiator *
       speech_initiator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpeechInitiator *)
     protobuf_c_message_unpack (&speech_initiator__descriptor,
                                allocator, len, data);
}
void   speech_initiator__free_unpacked
                     (SpeechInitiator *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech_initiator__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_speech__init
                     (StartSpeech         *message)
{
  static const StartSpeech init_value = START_SPEECH__INIT;
  *message = init_value;
}
size_t start_speech__get_packed_size
                     (const StartSpeech *message)
{
  assert(message->base.descriptor == &start_speech__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_speech__pack
                     (const StartSpeech *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_speech__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_speech__pack_to_buffer
                     (const StartSpeech *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_speech__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartSpeech *
       start_speech__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartSpeech *)
     protobuf_c_message_unpack (&start_speech__descriptor,
                                allocator, len, data);
}
void   start_speech__free_unpacked
                     (StartSpeech *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_speech__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speech_provider__init
                     (SpeechProvider         *message)
{
  static const SpeechProvider init_value = SPEECH_PROVIDER__INIT;
  *message = init_value;
}
size_t speech_provider__get_packed_size
                     (const SpeechProvider *message)
{
  assert(message->base.descriptor == &speech_provider__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech_provider__pack
                     (const SpeechProvider *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech_provider__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech_provider__pack_to_buffer
                     (const SpeechProvider *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech_provider__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpeechProvider *
       speech_provider__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpeechProvider *)
     protobuf_c_message_unpack (&speech_provider__descriptor,
                                allocator, len, data);
}
void   speech_provider__free_unpacked
                     (SpeechProvider *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech_provider__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   provide_speech__init
                     (ProvideSpeech         *message)
{
  static const ProvideSpeech init_value = PROVIDE_SPEECH__INIT;
  *message = init_value;
}
size_t provide_speech__get_packed_size
                     (const ProvideSpeech *message)
{
  assert(message->base.descriptor == &provide_speech__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t provide_speech__pack
                     (const ProvideSpeech *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &provide_speech__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t provide_speech__pack_to_buffer
                     (const ProvideSpeech *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &provide_speech__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProvideSpeech *
       provide_speech__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProvideSpeech *)
     protobuf_c_message_unpack (&provide_speech__descriptor,
                                allocator, len, data);
}
void   provide_speech__free_unpacked
                     (ProvideSpeech *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &provide_speech__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stop_speech__init
                     (StopSpeech         *message)
{
  static const StopSpeech init_value = STOP_SPEECH__INIT;
  *message = init_value;
}
size_t stop_speech__get_packed_size
                     (const StopSpeech *message)
{
  assert(message->base.descriptor == &stop_speech__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stop_speech__pack
                     (const StopSpeech *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stop_speech__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stop_speech__pack_to_buffer
                     (const StopSpeech *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stop_speech__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StopSpeech *
       stop_speech__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StopSpeech *)
     protobuf_c_message_unpack (&stop_speech__descriptor,
                                allocator, len, data);
}
void   stop_speech__free_unpacked
                     (StopSpeech *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stop_speech__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   endpoint_speech__init
                     (EndpointSpeech         *message)
{
  static const EndpointSpeech init_value = ENDPOINT_SPEECH__INIT;
  *message = init_value;
}
size_t endpoint_speech__get_packed_size
                     (const EndpointSpeech *message)
{
  assert(message->base.descriptor == &endpoint_speech__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t endpoint_speech__pack
                     (const EndpointSpeech *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &endpoint_speech__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t endpoint_speech__pack_to_buffer
                     (const EndpointSpeech *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &endpoint_speech__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndpointSpeech *
       endpoint_speech__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndpointSpeech *)
     protobuf_c_message_unpack (&endpoint_speech__descriptor,
                                allocator, len, data);
}
void   endpoint_speech__free_unpacked
                     (EndpointSpeech *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &endpoint_speech__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notify_speech_state__init
                     (NotifySpeechState         *message)
{
  static const NotifySpeechState init_value = NOTIFY_SPEECH_STATE__INIT;
  *message = init_value;
}
size_t notify_speech_state__get_packed_size
                     (const NotifySpeechState *message)
{
  assert(message->base.descriptor == &notify_speech_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_speech_state__pack
                     (const NotifySpeechState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_speech_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_speech_state__pack_to_buffer
                     (const NotifySpeechState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_speech_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifySpeechState *
       notify_speech_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifySpeechState *)
     protobuf_c_message_unpack (&notify_speech_state__descriptor,
                                allocator, len, data);
}
void   notify_speech_state__free_unpacked
                     (NotifySpeechState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_speech_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dialog__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dialog, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dialog__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange dialog__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dialog__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Dialog",
  "Dialog",
  "Dialog",
  "",
  sizeof(Dialog),
  1,
  dialog__field_descriptors,
  dialog__field_indices_by_name,
  1,  dialog__number_ranges,
  (ProtobufCMessageInit) dialog__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech_settings__field_descriptors[3] =
{
  {
    "audio_profile",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SpeechSettings, audio_profile),
    &audio_profile__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio_format",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SpeechSettings, audio_format),
    &audio_format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio_source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SpeechSettings, audio_source),
    &audio_source__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech_settings__field_indices_by_name[] = {
  1,   /* field[1] = audio_format */
  0,   /* field[0] = audio_profile */
  2,   /* field[2] = audio_source */
};
static const ProtobufCIntRange speech_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor speech_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeechSettings",
  "SpeechSettings",
  "SpeechSettings",
  "",
  sizeof(SpeechSettings),
  3,
  speech_settings__field_descriptors,
  speech_settings__field_indices_by_name,
  1,  speech_settings__number_ranges,
  (ProtobufCMessageInit) speech_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech_initiator__wake_word__field_descriptors[4] =
{
  {
    "start_index_in_samples",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator__WakeWord, start_index_in_samples),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_index_in_samples",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator__WakeWord, end_index_in_samples),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "near_miss",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator__WakeWord, near_miss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator__WakeWord, metadata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech_initiator__wake_word__field_indices_by_name[] = {
  1,   /* field[1] = end_index_in_samples */
  3,   /* field[3] = metadata */
  2,   /* field[2] = near_miss */
  0,   /* field[0] = start_index_in_samples */
};
static const ProtobufCIntRange speech_initiator__wake_word__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor speech_initiator__wake_word__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeechInitiator.WakeWord",
  "WakeWord",
  "SpeechInitiator__WakeWord",
  "",
  sizeof(SpeechInitiator__WakeWord),
  4,
  speech_initiator__wake_word__field_descriptors,
  speech_initiator__wake_word__field_indices_by_name,
  1,  speech_initiator__wake_word__number_ranges,
  (ProtobufCMessageInit) speech_initiator__wake_word__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue speech_initiator__type__enum_values_by_number[4] =
{
  { "NONE", "SPEECH_INITIATOR__TYPE__NONE", 0 },
  { "PRESS_AND_HOLD", "SPEECH_INITIATOR__TYPE__PRESS_AND_HOLD", 1 },
  { "TAP", "SPEECH_INITIATOR__TYPE__TAP", 3 },
  { "WAKEWORD", "SPEECH_INITIATOR__TYPE__WAKEWORD", 4 },
};
static const ProtobufCIntRange speech_initiator__type__value_ranges[] = {
{0, 0},{3, 2},{0, 4}
};
static const ProtobufCEnumValueIndex speech_initiator__type__enum_values_by_name[4] =
{
  { "NONE", 0 },
  { "PRESS_AND_HOLD", 1 },
  { "TAP", 2 },
  { "WAKEWORD", 3 },
};
const ProtobufCEnumDescriptor speech_initiator__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SpeechInitiator.Type",
  "Type",
  "SpeechInitiator__Type",
  "",
  4,
  speech_initiator__type__enum_values_by_number,
  4,
  speech_initiator__type__enum_values_by_name,
  2,
  speech_initiator__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor speech_initiator__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator, type),
    &speech_initiator__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wake_word",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SpeechInitiator, wake_word),
    &speech_initiator__wake_word__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech_initiator__field_indices_by_name[] = {
  0,   /* field[0] = type */
  1,   /* field[1] = wake_word */
};
static const ProtobufCIntRange speech_initiator__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor speech_initiator__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeechInitiator",
  "SpeechInitiator",
  "SpeechInitiator",
  "",
  sizeof(SpeechInitiator),
  2,
  speech_initiator__field_descriptors,
  speech_initiator__field_indices_by_name,
  1,  speech_initiator__number_ranges,
  (ProtobufCMessageInit) speech_initiator__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_speech__field_descriptors[4] =
{
  {
    "settings",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartSpeech, settings),
    &speech_settings__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initiator",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartSpeech, initiator),
    &speech_initiator__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dialog",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartSpeech, dialog),
    &dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suppressEarcon",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(StartSpeech, suppressearcon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_speech__field_indices_by_name[] = {
  2,   /* field[2] = dialog */
  1,   /* field[1] = initiator */
  0,   /* field[0] = settings */
  3,   /* field[3] = suppressEarcon */
};
static const ProtobufCIntRange start_speech__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor start_speech__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartSpeech",
  "StartSpeech",
  "StartSpeech",
  "",
  sizeof(StartSpeech),
  4,
  start_speech__field_descriptors,
  start_speech__field_indices_by_name,
  1,  start_speech__number_ranges,
  (ProtobufCMessageInit) start_speech__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech_provider__field_descriptors[2] =
{
  {
    "speech_settings",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SpeechProvider, speech_settings),
    &speech_settings__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dialog",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SpeechProvider, dialog),
    &dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech_provider__field_indices_by_name[] = {
  1,   /* field[1] = dialog */
  0,   /* field[0] = speech_settings */
};
static const ProtobufCIntRange speech_provider__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor speech_provider__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeechProvider",
  "SpeechProvider",
  "SpeechProvider",
  "",
  sizeof(SpeechProvider),
  2,
  speech_provider__field_descriptors,
  speech_provider__field_indices_by_name,
  1,  speech_provider__number_ranges,
  (ProtobufCMessageInit) speech_provider__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor provide_speech__field_descriptors[1] =
{
  {
    "dialog",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProvideSpeech, dialog),
    &dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned provide_speech__field_indices_by_name[] = {
  0,   /* field[0] = dialog */
};
static const ProtobufCIntRange provide_speech__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor provide_speech__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProvideSpeech",
  "ProvideSpeech",
  "ProvideSpeech",
  "",
  sizeof(ProvideSpeech),
  1,
  provide_speech__field_descriptors,
  provide_speech__field_indices_by_name,
  1,  provide_speech__number_ranges,
  (ProtobufCMessageInit) provide_speech__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stop_speech__field_descriptors[2] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StopSpeech, error_code),
    &error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dialog",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StopSpeech, dialog),
    &dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stop_speech__field_indices_by_name[] = {
  1,   /* field[1] = dialog */
  0,   /* field[0] = error_code */
};
static const ProtobufCIntRange stop_speech__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stop_speech__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StopSpeech",
  "StopSpeech",
  "StopSpeech",
  "",
  sizeof(StopSpeech),
  2,
  stop_speech__field_descriptors,
  stop_speech__field_indices_by_name,
  1,  stop_speech__number_ranges,
  (ProtobufCMessageInit) stop_speech__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor endpoint_speech__field_descriptors[1] =
{
  {
    "dialog",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EndpointSpeech, dialog),
    &dialog__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned endpoint_speech__field_indices_by_name[] = {
  0,   /* field[0] = dialog */
};
static const ProtobufCIntRange endpoint_speech__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor endpoint_speech__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndpointSpeech",
  "EndpointSpeech",
  "EndpointSpeech",
  "",
  sizeof(EndpointSpeech),
  1,
  endpoint_speech__field_descriptors,
  endpoint_speech__field_indices_by_name,
  1,  endpoint_speech__number_ranges,
  (ProtobufCMessageInit) endpoint_speech__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor notify_speech_state__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NotifySpeechState, state),
    &speech_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify_speech_state__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange notify_speech_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor notify_speech_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifySpeechState",
  "NotifySpeechState",
  "NotifySpeechState",
  "",
  sizeof(NotifySpeechState),
  1,
  notify_speech_state__field_descriptors,
  notify_speech_state__field_indices_by_name,
  1,  notify_speech_state__number_ranges,
  (ProtobufCMessageInit) notify_speech_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue audio_profile__enum_values_by_number[3] =
{
  { "CLOSE_TALK", "AUDIO_PROFILE__CLOSE_TALK", 0 },
  { "NEAR_FIELD", "AUDIO_PROFILE__NEAR_FIELD", 1 },
  { "FAR_FIELD", "AUDIO_PROFILE__FAR_FIELD", 2 },
};
static const ProtobufCIntRange audio_profile__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex audio_profile__enum_values_by_name[3] =
{
  { "CLOSE_TALK", 0 },
  { "FAR_FIELD", 2 },
  { "NEAR_FIELD", 1 },
};
const ProtobufCEnumDescriptor audio_profile__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AudioProfile",
  "AudioProfile",
  "AudioProfile",
  "",
  3,
  audio_profile__enum_values_by_number,
  3,
  audio_profile__enum_values_by_name,
  1,
  audio_profile__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue audio_format__enum_values_by_number[4] =
{
  { "PCM_L16_16KHZ_MONO", "AUDIO_FORMAT__PCM_L16_16KHZ_MONO", 0 },
  { "OPUS_16KHZ_32KBPS_CBR_0_20MS", "AUDIO_FORMAT__OPUS_16KHZ_32KBPS_CBR_0_20MS", 1 },
  { "OPUS_16KHZ_16KBPS_CBR_0_20MS", "AUDIO_FORMAT__OPUS_16KHZ_16KBPS_CBR_0_20MS", 2 },
  { "MSBC", "AUDIO_FORMAT__MSBC", 3 },
};
static const ProtobufCIntRange audio_format__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex audio_format__enum_values_by_name[4] =
{
  { "MSBC", 3 },
  { "OPUS_16KHZ_16KBPS_CBR_0_20MS", 2 },
  { "OPUS_16KHZ_32KBPS_CBR_0_20MS", 1 },
  { "PCM_L16_16KHZ_MONO", 0 },
};
const ProtobufCEnumDescriptor audio_format__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AudioFormat",
  "AudioFormat",
  "AudioFormat",
  "",
  4,
  audio_format__enum_values_by_number,
  4,
  audio_format__enum_values_by_name,
  1,
  audio_format__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue audio_source__enum_values_by_number[2] =
{
  { "STREAM", "AUDIO_SOURCE__STREAM", 0 },
  { "BLUETOOTH_SCO", "AUDIO_SOURCE__BLUETOOTH_SCO", 1 },
};
static const ProtobufCIntRange audio_source__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex audio_source__enum_values_by_name[2] =
{
  { "BLUETOOTH_SCO", 1 },
  { "STREAM", 0 },
};
const ProtobufCEnumDescriptor audio_source__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AudioSource",
  "AudioSource",
  "AudioSource",
  "",
  2,
  audio_source__enum_values_by_number,
  2,
  audio_source__enum_values_by_name,
  1,
  audio_source__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue speech_state__enum_values_by_number[4] =
{
  { "IDLE", "SPEECH_STATE__IDLE", 0 },
  { "LISTENING", "SPEECH_STATE__LISTENING", 1 },
  { "PROCESSING", "SPEECH_STATE__PROCESSING", 2 },
  { "SPEAKING", "SPEECH_STATE__SPEAKING", 3 },
};
static const ProtobufCIntRange speech_state__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex speech_state__enum_values_by_name[4] =
{
  { "IDLE", 0 },
  { "LISTENING", 1 },
  { "PROCESSING", 2 },
  { "SPEAKING", 3 },
};
const ProtobufCEnumDescriptor speech_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SpeechState",
  "SpeechState",
  "SpeechState",
  "",
  4,
  speech_state__enum_values_by_number,
  4,
  speech_state__enum_values_by_name,
  1,
  speech_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
