/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_ama_server/gatt_ama_server_db.dbi_
 */
#ifndef __GATT_AMA_SERVER_DB_H
#define __GATT_AMA_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_AMA_ALEXA_SERVICE        (0x0001)
#define HANDLE_AMA_ALEXA_SERVICE_END    (0xffff)
#define HANDLE_AMA_ALEXA_TX_CHAR        (0x0003)
#define HANDLE_AMA_ALEXA_RX_CHAR       (0x0005)
#define HANDLE_AMA_ALEXA_RX_CLIENT_C_CFG (0x0006)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
