/****************************************************************************
Copyright (c) 2016 Qualcomm Technologies International, Ltd.


FILE NAME
    rsa_pss_constants.h

DESCRIPTION
    Header file for constant data needed for the rsa_decrypt and the
    ce_pkcs1_pss_padding_verify function.

NOTES
    The constant data for the rsa_decrypt is generated by the host from the
    RSA public key and compiled into the CONFIG_HYDRACORE VM upgrade library.
    It is directly related to the RSA private and public key pair, and if they
    change then this file must be regenerated from the public key.

    In this initial version this file contains dummy values. The rsa_decrypt
    function will not work with these values!

    The constant for the saltlen parameter to the ce_pkcs1_pss_padding_verify
    funtcion is also in this file.

*/

#ifndef __RSA_PSS_CONSTANTS_H__
#define __RSA_PSS_CONSTANTS_H__

#include <rsa_decrypt.h>

/* 
 * The const rsa_mod_t *mod parameter for the rsa_decrypt function.
 */
extern const rsa_mod_t rsa_decrypt_constant_mod;

/* 
 * The "lump of memory passed in initialised to R^2N mod M" needed for the
 * uint16 *A parameter for the rsa_decrypt function. This must be copied into
 * a writable array of RSA_SIGNATURE_SIZE uint16 from here before use.
 */
extern const  uint16 rsa_decrypt_constant_sign_r2n[RSA_SIGNATURE_SIZE];

/*
 * The value to be provided for the saltlen parameter to the 
 * ce_pkcs1_pss_padding_verify function used to decode the PSS padded SHA-256
 * hash. It has to match the value that was used in the encoding process.
 */
extern const unsigned long ce_pkcs1_pss_padding_verify_constant_saltlen;

#endif  /* __RSA_PSS_CONSTANTS_H__ */

