/****************************************************************************
Copyright (c) 2016-2017 Qualcomm Technologies International, Ltd.


FILE NAME
    rsa_pss_constants.c

DESCRIPTION
    Constant data needed for the rsa_decrypt and the ce_pkcs1_pss_padding_verify
    function.

NOTES
    The constant data for the rsa_decrypt is generated by the host from the
    RSA public key and compiled into the CONFIG_HYDRACORE VM upgrade library.
    It is directly related to the RSA private and public key pair, and if they
    change then this file must be regenerated from the public key.

The private.pem for this data is:

-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDArYKc6pGiFFuG
dkvgU3PVdeh3NY+7zXa1yPVBI7gAh+TVqA3iZgfbWSb5P7F0y/9xxI9mLsNcWzQ7
lkltc+UgPfNExPkpRJtSz518pAg62wmEVowzcpFGmrBDXENh51Wn7UVeWsk6BxwR
R3w+PwDlBL3kAYq8sCNqCJ8+zxWV8R+/GrSLBu4FBSed8FBrXhZmVPCpM2pmypSz
JbDLQR3z8lwA3hJrfrDnPZ0HoWyhyDqfgVaZIpFBfuefr63wj5//pcckE12Is2Kx
wOpXtJmxsQyClObu6L10Z6hMtQu4X31XGW9var5I2Td6j1rSBrpgef/vUjHViQc+
aNhhU+TnAgMBAAECggEBAJUWLNhqEGHPSrqSUkeziw+CemuzQBJa+x3R7yOGFdwj
Soefz4580FuDckquZAsxxegr5aF1Uajm0VXCBfLxGDuIc/GkT/8EnQLIrt1AtzWD
Qqvpo/YzEgIFs5mLjH/21ipnx6MosEd8NNWR8KrhaTnMH3qLTuSNjfl/zmh1KAiq
AL60aqyo0poTHyyJJGEkkMG36/Nrc4K4qrahN1xdJP/Ew4LWwLRCmF6r5QZWn7c0
Nf1cMLARBywRvr9FVGG/CBG1sMoWa7NaXtaa8tAw053I0bXkj6/5BrBUU8mdF4gF
s8UfHcyAWmfHtJ/WAPJfFaWpbFPlUaIogi1bx0arxtECgYEA5R3G/fIGH5h4Jw5H
atZz93K7me3TrmkYR1Bz+6+hdykSnPjBpcKN93QlBtAsoKmdoI0FGswVXnJQThA0
RN1m3W5vNxuehTxq6KOiHhvVO6b2d1jL9GvKeK7UjDVEDNQ0RehIExgSSGOY4AQ9
QeHdFZwg41M8GySOiMKCGdo9mv0CgYEA10kwC4Zq9LdMKlpT6Kt5yUzpCxI1Pjdo
bZjp1avxObQyu+nw492eM5UE9eGJJCTlFJ39TwN5S/wY6H2kFNflHRHV1Zwp+r+y
graQPICsOpmDXeQEELA0x+E2zkbzoVH5OBXC1kzf5GHabzELaC9GyuDDwzKJtR7C
JzgxjptYfrMCgYArgCLW9ku5Vf6CE9D1dPAhrDP4PtJxC90jNSBAShFTCYZSLVy+
9xhzQicBiybd/jZCVGQCuXrZKsUafTMfXBX6tswA34qSa2007FSMeOZcZA/piv92
UbzoevE6Cab49JVULIz6qxhVjCtrZQKobpTGVJVd8+C2mpNBXgTLmccWlQKBgDC5
xt8E6FZE2j9HvHAPx3uxJZm04EoZnlAX6OzMgsdtqoHve+8G7NR96OaByllc5GBb
NcbZYW26PCT6stVo29lNfRlgw/uVwaBmE5UuBk0pC5uHjQf96aRHq/DaDDA57m8s
NbHtKkt1fkvmTM+iy6IFZylZ2eMdeBIKXOUK8eeTAoGAd3iHG1C/1fyEO0iLwMFP
l44u8Ge20PaiM/2nrj7eqzaoN8voNLGDABmXovVleKyvpqh5ypZU7xZ2QmLRHvNl
IOvOBhPa9RVUV5DjO7J261/ujVwv5QxuICwNnKy9pS5ALMLI+BJJ5BttGOTkn7BY
5KSRuDRpduGBdm3LLVi/DyE=
-----END PRIVATE KEY-----

****************************************************************************/

#include <rsa_decrypt.h>

/*
 * The const rsa_mod_t *mod parameter for the rsa_decrypt function.
 */
const rsa_mod_t rsa_decrypt_constant_mod = {
    /* uint16 M[RSA_SIGNATURE_SIZE] where RSA_SIGNATURE_SIZE is 128 */
    {
        0xc0ad,     /* 00 */
        0x829c,     /* 01 */
        0xea91,     /* 02 */
        0xa214,     /* 03 */
        0x5b86,     /* 04 */
        0x764b,     /* 05 */
        0xe053,     /* 06 */
        0x73d5,     /* 07 */
        0x75e8,     /* 08 */
        0x7735,     /* 09 */
        0x8fbb,     /* 10 */
        0xcd76,     /* 11 */
        0xb5c8,     /* 12 */
        0xf541,     /* 13 */
        0x23b8,     /* 14 */
        0x0087,     /* 15 */
        0xe4d5,     /* 16 */
        0xa80d,     /* 17 */
        0xe266,     /* 18 */
        0x07db,     /* 19 */
        0x5926,     /* 20 */
        0xf93f,     /* 21 */
        0xb174,     /* 22 */
        0xcbff,     /* 23 */
        0x71c4,     /* 24 */
        0x8f66,     /* 25 */
        0x2ec3,     /* 26 */
        0x5c5b,     /* 27 */
        0x343b,     /* 28 */
        0x9649,     /* 29 */
        0x6d73,     /* 30 */
        0xe520,     /* 31 */
        0x3df3,     /* 32 */
        0x44c4,     /* 33 */
        0xf929,     /* 34 */
        0x449b,     /* 35 */
        0x52cf,     /* 36 */
        0x9d7c,     /* 37 */
        0xa408,     /* 38 */
        0x3adb,     /* 39 */
        0x0984,     /* 40 */
        0x568c,     /* 41 */
        0x3372,     /* 42 */
        0x9146,     /* 43 */
        0x9ab0,     /* 44 */
        0x435c,     /* 45 */
        0x4361,     /* 46 */
        0xe755,     /* 47 */
        0xa7ed,     /* 48 */
        0x455e,     /* 49 */
        0x5ac9,     /* 50 */
        0x3a07,     /* 51 */
        0x1c11,     /* 52 */
        0x477c,     /* 53 */
        0x3e3f,     /* 54 */
        0x00e5,     /* 55 */
        0x04bd,     /* 56 */
        0xe401,     /* 57 */
        0x8abc,     /* 58 */
        0xb023,     /* 59 */
        0x6a08,     /* 60 */
        0x9f3e,     /* 61 */
        0xcf15,     /* 62 */
        0x95f1,     /* 63 */
        0x1fbf,     /* 64 */
        0x1ab4,     /* 65 */
        0x8b06,     /* 66 */
        0xee05,     /* 67 */
        0x0527,     /* 68 */
        0x9df0,     /* 69 */
        0x506b,     /* 70 */
        0x5e16,     /* 71 */
        0x6654,     /* 72 */
        0xf0a9,     /* 73 */
        0x336a,     /* 74 */
        0x66ca,     /* 75 */
        0x94b3,     /* 76 */
        0x25b0,     /* 77 */
        0xcb41,     /* 78 */
        0x1df3,     /* 79 */
        0xf25c,     /* 80 */
        0x00de,     /* 81 */
        0x126b,     /* 82 */
        0x7eb0,     /* 83 */
        0xe73d,     /* 84 */
        0x9d07,     /* 85 */
        0xa16c,     /* 86 */
        0xa1c8,     /* 87 */
        0x3a9f,     /* 88 */
        0x8156,     /* 89 */
        0x9922,     /* 90 */
        0x9141,     /* 91 */
        0x7ee7,     /* 92 */
        0x9faf,     /* 93 */
        0xadf0,     /* 94 */
        0x8f9f,     /* 95 */
        0xffa5,     /* 96 */
        0xc724,     /* 97 */
        0x135d,     /* 98 */
        0x88b3,     /* 99 */
        0x62b1,     /* 100 */
        0xc0ea,     /* 101 */
        0x57b4,     /* 102 */
        0x99b1,     /* 103 */
        0xb10c,     /* 104 */
        0x8294,     /* 105 */
        0xe6ee,     /* 106 */
        0xe8bd,     /* 107 */
        0x7467,     /* 108 */
        0xa84c,     /* 109 */
        0xb50b,     /* 110 */
        0xb85f,     /* 111 */
        0x7d57,     /* 112 */
        0x196f,     /* 113 */
        0x6f6a,     /* 114 */
        0xbe48,     /* 115 */
        0xd937,     /* 116 */
        0x7a8f,     /* 117 */
        0x5ad2,     /* 118 */
        0x06ba,     /* 119 */
        0x6079,     /* 120 */
        0xffef,     /* 121 */
        0x5231,     /* 122 */
        0xd589,     /* 123 */
        0x073e,     /* 124 */
        0x68d8,     /* 125 */
        0x6153,     /* 126 */
        0xe4e7      /* 127 */
    },
    /* uint16 M_dash */
    0x1129
};

/* 
 * The "lump of memory passed in initialised to R^2N mod M" needed for the
 * uint16 *A parameter for the rsa_decrypt function. This must be copied into
 * a writable array of RSA_SIGNATURE_SIZE uint16 from here before use.
 */
const  uint16 rsa_decrypt_constant_sign_r2n[RSA_SIGNATURE_SIZE] = {
    0x8bdb,     /* 00 */
    0xd984,     /* 01 */
    0x3aba,     /* 02 */
    0x6d2a,     /* 03 */
    0xfda9,     /* 04 */
    0x936f,     /* 05 */
    0x8c75,     /* 06 */
    0xf689,     /* 07 */
    0x2ae7,     /* 08 */
    0xb9eb,     /* 09 */
    0x9de8,     /* 10 */
    0xd9e9,     /* 11 */
    0x66eb,     /* 12 */
    0xf9b1,     /* 13 */
    0x58c8,     /* 14 */
    0x0272,     /* 15 */
    0x3410,     /* 16 */
    0xd09e,     /* 17 */
    0xf004,     /* 18 */
    0x76c0,     /* 19 */
    0x3a57,     /* 20 */
    0x64ff,     /* 21 */
    0x9ace,     /* 22 */
    0x3555,     /* 23 */
    0x849a,     /* 24 */
    0x0b38,     /* 25 */
    0x07ac,     /* 26 */
    0xa27d,     /* 27 */
    0xc4d5,     /* 28 */
    0x8ac9,     /* 29 */
    0xbb04,     /* 30 */
    0x0348,     /* 31 */
    0x07b1,     /* 32 */
    0xb5bf,     /* 33 */
    0x0908,     /* 34 */
    0x6ae9,     /* 35 */
    0x6774,     /* 36 */
    0x174b,     /* 37 */
    0xf88d,     /* 38 */
    0xa7c3,     /* 39 */
    0x9262,     /* 40 */
    0x7cc9,     /* 41 */
    0x15cf,     /* 42 */
    0x5902,     /* 43 */
    0x6f26,     /* 44 */
    0xae6d,     /* 45 */
    0xdacf,     /* 46 */
    0x722c,     /* 47 */
    0x602d,     /* 48 */
    0x91f1,     /* 49 */
    0xb260,     /* 50 */
    0xdc2d,     /* 51 */
    0xfaf0,     /* 52 */
    0xcf87,     /* 53 */
    0x4812,     /* 54 */
    0x9663,     /* 55 */
    0x7540,     /* 56 */
    0x7dbe,     /* 57 */
    0x8897,     /* 58 */
    0x5af9,     /* 59 */
    0xc53f,     /* 60 */
    0x5082,     /* 61 */
    0xcad3,     /* 62 */
    0x0058,     /* 63 */
    0xb3c5,     /* 64 */
    0x4499,     /* 65 */
    0x43ba,     /* 66 */
    0x62df,     /* 67 */
    0x1a71,     /* 68 */
    0x6025,     /* 69 */
    0x2f92,     /* 70 */
    0x0ffb,     /* 71 */
    0xb180,     /* 72 */
    0xa597,     /* 73 */
    0xbfbc,     /* 74 */
    0x5d1e,     /* 75 */
    0x656d,     /* 76 */
    0xcce2,     /* 77 */
    0xbee6,     /* 78 */
    0x92b1,     /* 79 */
    0xe2c4,     /* 80 */
    0x2ed7,     /* 81 */
    0xa465,     /* 82 */
    0x1445,     /* 83 */
    0xed80,     /* 84 */
    0x9f2b,     /* 85 */
    0x42a3,     /* 86 */
    0xc86f,     /* 87 */
    0x8db5,     /* 88 */
    0x994d,     /* 89 */
    0xa868,     /* 90 */
    0xa746,     /* 91 */
    0x2a57,     /* 92 */
    0x2f60,     /* 93 */
    0x8b86,     /* 94 */
    0x32a1,     /* 95 */
    0x4aa4,     /* 96 */
    0xd230,     /* 97 */
    0xba60,     /* 98 */
    0xf3a2,     /* 99 */
    0x5e83,     /* 100 */
    0x91e7,     /* 101 */
    0xbbfd,     /* 102 */
    0x7d98,     /* 103 */
    0xaccf,     /* 104 */
    0xe19d,     /* 105 */
    0x0ca5,     /* 106 */
    0x23c7,     /* 107 */
    0x20a0,     /* 108 */
    0x516d,     /* 109 */
    0xe261,     /* 110 */
    0xb984,     /* 111 */
    0x7921,     /* 112 */
    0xd220,     /* 113 */
    0x25ee,     /* 114 */
    0x6e7d,     /* 115 */
    0x1e87,     /* 116 */
    0x8e9d,     /* 117 */
    0x3c80,     /* 118 */
    0xc8cc,     /* 119 */
    0xdb27,     /* 120 */
    0x0abd,     /* 121 */
    0xc182,     /* 122 */
    0xd7af,     /* 123 */
    0x7a85,     /* 124 */
    0x1ee5,     /* 125 */
    0xeee1,     /* 126 */
    0x8c93      /* 127 */
};

/*
 * The value to be provided for the saltlen parameter to the 
 * ce_pkcs1_pss_padding_verify function used to decode the PSS padded SHA-256
 * hash. It has to match the value that was used in the encoding process.
 */
const unsigned long ce_pkcs1_pss_padding_verify_constant_saltlen = 222;
