#ifndef __API_H__
#define __API_H__
/** \file */
/*
 * This file is autogenerated from api.xml by api_codegen.py
 *
 * Copyright (c) 2019 Qualcomm Technologies International, Ltd.
 */
/**
 * \defgroup api Customer Trap API
 */
/*
 * Version 9.7
 */


/*
 * TRAPSETS
 */
/**
 * \defgroup trapset_fastpipe FASTPIPE
 * \ingroup api
 */
/**
 * \defgroup trapset_charger CHARGER
 * \ingroup api
 */
/**
 * \defgroup trapset_file FILE
 * \ingroup api
 */
/**
 * \defgroup trapset_voice VOICE
 * \ingroup api
 */
/**
 * \defgroup trapset_uart UART
 * \ingroup api
 */
/**
 * \defgroup trapset_hoststream HOSTSTREAM
 * \ingroup api
 */
/**
 * \defgroup trapset_energy ENERGY
 * \ingroup api
 */
/**
 * \defgroup trapset_capacitive_sensor CAPACITIVE_SENSOR
 * \ingroup api
 */
/**
 * \defgroup trapset_rtscts RTSCTS
 * \ingroup api
 */
/**
 * \defgroup trapset_audio AUDIO
 * \ingroup api
 */
/**
 * \defgroup trapset_pioex1 PIOEX1
 * \ingroup api
 */
/**
 * \defgroup trapset_kalimba KALIMBA
 * \ingroup api
 */
/**
 * \defgroup trapset_rfcomm RFCOMM
 * \ingroup api
 */
/**
 * \defgroup trapset_font FONT
 * \ingroup api
 */
/**
 * \defgroup trapset_bluestack BLUESTACK
 * \ingroup api
 */
/**
 * \defgroup trapset_reformatsqif REFORMATSQIF
 * \ingroup api
 */
/**
 * \defgroup trapset_operator OPERATOR
 * \ingroup api
 */
/**
 * \defgroup trapset_lcd LCD
 * \ingroup api
 */
/**
 * \defgroup trapset_chargermessage CHARGERMESSAGE
 * \ingroup api
 */
/**
 * \defgroup trapset_psu PSU
 * \ingroup api
 */
/**
 * \defgroup trapset_micbias MICBIAS
 * \ingroup api
 */
/**
 * \defgroup trapset_stream STREAM
 * \ingroup api
 */
/**
 * \defgroup trapset_infrared INFRARED
 * \ingroup api
 */
/**
 * \defgroup trapset_att ATT
 * \ingroup api
 */
/**
 * \defgroup trapset_hiddongle HIDDONGLE
 * \ingroup api
 */
/**
 * \defgroup trapset_native NATIVE
 * \ingroup api
 */
/**
 * \defgroup trapset_spiflash SPIFLASH
 * \ingroup api
 */
/**
 * \defgroup trapset_core CORE
 * \ingroup api
 */
/**
 * \defgroup trapset_ldrupgrade LDRUPGRADE
 * \ingroup api
 */
/**
 * \defgroup trapset_partition PARTITION
 * \ingroup api
 */
/**
 * \defgroup trapset_amuxclock AMUXCLOCK
 * \ingroup api
 */
/**
 * \defgroup trapset_host HOST
 * \ingroup api
 */
/**
 * \defgroup trapset_sqifexecute SQIFEXECUTE
 * \ingroup api
 */
/**
 * \defgroup trapset_md5 MD5
 * \ingroup api
 */
/**
 * \defgroup trapset_led LED
 * \ingroup api
 */
/**
 * \defgroup trapset_bc7 BC7
 * \ingroup api
 */
/**
 * \defgroup trapset_usb USB
 * \ingroup api
 */
/**
 * \defgroup trapset_usb_hub USB_HUB
 * \ingroup api
 */
/**
 * \defgroup trapset_sram SRAM
 * \ingroup api
 */
/**
 * \defgroup trapset_charger2 CHARGER2
 * \ingroup api
 */
/**
 * \defgroup trapset_shunt SHUNT
 * \ingroup api
 */
/**
 * \defgroup trapset_iicstream IICSTREAM
 * \ingroup api
 */
/**
 * \defgroup trapset_iir IIR
 * \ingroup api
 */
/**
 * \defgroup trapset_otp OTP
 * \ingroup api
 */
/**
 * \defgroup trapset_iic IIC
 * \ingroup api
 */
/**
 * \defgroup trapset_status STATUS
 * \ingroup api
 */
/**
 * \defgroup trapset_auxdac AUXDAC
 * \ingroup api
 */
/**
 * \defgroup trapset_test TEST
 * \ingroup api
 */
/**
 * \defgroup trapset_ble3dd BLE3DD
 * \ingroup api
 */
/**
 * \defgroup trapset_iir16bit IIR16BIT
 * \ingroup api
 */
/**
 * \defgroup trapset_nfc NFC
 * \ingroup api
 */
/**
 * \defgroup trapset_sd_mmc SD_MMC
 * \ingroup api
 */
/**
 * \defgroup trapset_imageupgrade IMAGEUPGRADE
 * \ingroup api
 */
/**
 * \defgroup trapset_csb CSB
 * \ingroup api
 */
/**
 * \defgroup trapset_audio_mclk AUDIO_MCLK
 * \ingroup api
 */
/**
 * \defgroup trapset_crypto CRYPTO
 * \ingroup api
 */
/**
 * \defgroup trapset_audio_pwm AUDIO_PWM
 * \ingroup api
 */
/**
 * \defgroup trapset_xio XIO
 * \ingroup api
 */
/**
 * \defgroup trapset_bitserial BITSERIAL
 * \ingroup api
 */
/**
 * \defgroup trapset_audio_anc AUDIO_ANC
 * \ingroup api
 */
/**
 * \defgroup trapset_wake_on_audio WAKE_ON_AUDIO
 * \ingroup api
 */
/**
 * \defgroup trapset_profile PROFILE
 * \ingroup api
 */
/**
 * \defgroup trapset_bdaddr BDADDR
 * \ingroup api
 */
#endif
