/*!
\copyright  Copyright (c) 2018 Qualcomm Technologies International, Ltd.
            All Rights Reserved.
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\brief      Thermistor temperature voltage lookup table.
\note       Auto-generated by thermistor.py using constants:
                Namespace(BETA=3380.0, R0=10000.0, R_DIVIDER=10000.0, T0=25.0, TEMP_MAX=85, TEMP_MIN=-40, V_DIVIDER=1.8)
*/

#include "types.h"

/*! \brief The temperature corresponding to the first entry in #thermistor_voltage_lookup_table */
#define THERMISTOR_TEMP_MIN -40
/*! \brief The temperature corresponding to the final entry in #thermistor_voltage_lookup_table */
#define THERMISTOR_TEMP_MAX 85

/*! \brief A table of expected thermistor milli-voltage against temperature in the
           range THERMISTOR_TEMP_MIN to THERMISTOR_TEMP_MAX degrees Celsius */
static const uint16 thermistor_voltage_lookup_table[THERMISTOR_TEMP_MAX-THERMISTOR_TEMP_MIN+1] = {
    1726, // -40C
    1722, // -39C
    1717, // -38C
    1712, // -37C
    1707, // -36C
    1702, // -35C
    1696, // -34C
    1690, // -33C
    1684, // -32C
    1678, // -31C
    1671, // -30C
    1664, // -29C
    1657, // -28C
    1649, // -27C
    1641, // -26C
    1633, // -25C
    1625, // -24C
    1616, // -23C
    1607, // -22C
    1597, // -21C
    1588, // -20C
    1578, // -19C
    1567, // -18C
    1557, // -17C
    1546, // -16C
    1535, // -15C
    1523, // -14C
    1511, // -13C
    1499, // -12C
    1486, // -11C
    1473, // -10C
    1460, // -9C
    1447, // -8C
    1433, // -7C
    1419, // -6C
    1404, // -5C
    1390, // -4C
    1375, // -3C
    1360, // -2C
    1344, // -1C
    1329, // 0C
    1313, // 1C
    1297, // 2C
    1280, // 3C
    1264, // 4C
    1247, // 5C
    1230, // 6C
    1214, // 7C
    1196, // 8C
    1179, // 9C
    1162, // 10C
    1145, // 11C
    1127, // 12C
    1109, // 13C
    1092, // 14C
    1074, // 15C
    1057, // 16C
    1039, // 17C
    1021, // 18C
    1004, // 19C
    986, // 20C
    969, // 21C
    951, // 22C
    934, // 23C
    917, // 24C
    900, // 25C
    882, // 26C
    866, // 27C
    849, // 28C
    832, // 29C
    816, // 30C
    799, // 31C
    783, // 32C
    767, // 33C
    751, // 34C
    736, // 35C
    720, // 36C
    705, // 37C
    690, // 38C
    676, // 39C
    661, // 40C
    647, // 41C
    633, // 42C
    619, // 43C
    605, // 44C
    592, // 45C
    579, // 46C
    566, // 47C
    553, // 48C
    541, // 49C
    528, // 50C
    516, // 51C
    505, // 52C
    493, // 53C
    482, // 54C
    471, // 55C
    460, // 56C
    449, // 57C
    439, // 58C
    429, // 59C
    419, // 60C
    409, // 61C
    400, // 62C
    391, // 63C
    382, // 64C
    373, // 65C
    364, // 66C
    356, // 67C
    347, // 68C
    339, // 69C
    331, // 70C
    324, // 71C
    316, // 72C
    309, // 73C
    302, // 74C
    295, // 75C
    288, // 76C
    281, // 77C
    275, // 78C
    269, // 79C
    262, // 80C
    256, // 81C
    251, // 82C
    245, // 83C
    239, // 84C
    234, // 85C
};

