/*!
\copyright  Copyright (c) 2018 Qualcomm Technologies International, Ltd.
            All Rights Reserved.
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\brief      Thermistor temperature voltage lookup table.
\note       Auto-generated by thermistor.py using constants:
                Namespace(BETA=3435.0, R0=10000.0, R_DIVIDER=10000.0, T0=25.0, TEMP_MAX=85, TEMP_MIN=-40, V_DIVIDER=1.8)
*/

#include "types.h"

/*! \brief The temperature corresponding to the first entry in #thermistor_voltage_lookup_table */
#define THERMISTOR_TEMP_MIN -40
/*! \brief The temperature corresponding to the final entry in #thermistor_voltage_lookup_table */
#define THERMISTOR_TEMP_MAX 85

/*! \brief A table of expected thermistor milli-voltage against temperature in the
           range THERMISTOR_TEMP_MIN to THERMISTOR_TEMP_MAX degrees Celsius */
static const uint16 thermistor_voltage_lookup_table[THERMISTOR_TEMP_MAX-THERMISTOR_TEMP_MIN+1] = {
    1730, // -40C
    1725, // -39C
    1721, // -38C
    1716, // -37C
    1711, // -36C
    1706, // -35C
    1700, // -34C
    1695, // -33C
    1689, // -32C
    1682, // -31C
    1676, // -30C
    1669, // -29C
    1662, // -28C
    1654, // -27C
    1647, // -26C
    1639, // -25C
    1630, // -24C
    1622, // -23C
    1613, // -22C
    1603, // -21C
    1594, // -20C
    1584, // -19C
    1574, // -18C
    1563, // -17C
    1552, // -16C
    1541, // -15C
    1529, // -14C
    1517, // -13C
    1505, // -12C
    1493, // -11C
    1480, // -10C
    1467, // -9C
    1453, // -8C
    1439, // -7C
    1425, // -6C
    1411, // -5C
    1396, // -4C
    1381, // -3C
    1366, // -2C
    1350, // -1C
    1334, // 0C
    1318, // 1C
    1302, // 2C
    1286, // 3C
    1269, // 4C
    1252, // 5C
    1235, // 6C
    1218, // 7C
    1201, // 8C
    1183, // 9C
    1166, // 10C
    1148, // 11C
    1131, // 12C
    1113, // 13C
    1095, // 14C
    1077, // 15C
    1059, // 16C
    1041, // 17C
    1023, // 18C
    1005, // 19C
    988, // 20C
    970, // 21C
    952, // 22C
    934, // 23C
    917, // 24C
    900, // 25C
    882, // 26C
    865, // 27C
    848, // 28C
    831, // 29C
    814, // 30C
    798, // 31C
    781, // 32C
    765, // 33C
    749, // 34C
    733, // 35C
    718, // 36C
    702, // 37C
    687, // 38C
    672, // 39C
    657, // 40C
    643, // 41C
    629, // 42C
    614, // 43C
    601, // 44C
    587, // 45C
    574, // 46C
    561, // 47C
    548, // 48C
    535, // 49C
    523, // 50C
    511, // 51C
    499, // 52C
    487, // 53C
    476, // 54C
    465, // 55C
    454, // 56C
    443, // 57C
    433, // 58C
    423, // 59C
    413, // 60C
    403, // 61C
    394, // 62C
    384, // 63C
    375, // 64C
    366, // 65C
    358, // 66C
    349, // 67C
    341, // 68C
    333, // 69C
    325, // 70C
    317, // 71C
    310, // 72C
    302, // 73C
    295, // 74C
    288, // 75C
    282, // 76C
    275, // 77C
    269, // 78C
    262, // 79C
    256, // 80C
    250, // 81C
    244, // 82C
    239, // 83C
    233, // 84C
    228, // 85C
};

